### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by MAleemH** [Fene-87/catalog_of_things#32]
Please click [here](https://github.com/Fene-87/catalog_of_things/projects/1]) to visit Kanban board.

There are four team members in this group project. Team members and their tasks are listed below:

1. Team member 1: @MAleemH 
2. Team member 2: @EmekaEmmanuel 
3. Team member 3: @Fene-87 
4. Team member 4: @shasherazi

**Comment by brytebee** [comment]
Hi, Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
